name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_wheel_and_sdist:
    name: Build wheel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install --upgrade build
      - name: Build wheel and sdist
        run: python -m build
      - name: Validate Build Artifacts
        run: tar -tzf dist/idascript-*.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: artifact_${{ matrix.python-version }}
          path: |
            dist/idascript*.whl
            dist/idascript*.tar.gz

  upload_pypi:
    needs: build_wheel_and_sdist
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/idascript
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact_*
          merge-multiple: true
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist/
          attestations: true
        # with:
        #  password: ${{ secrets.PYPI_DEPLOY_TOKEN }}

  upload_artifacts_release:
    needs: build_wheel_and_sdist
    runs-on: ubuntu-latest
    steps:
      - name: Upload Python packages for release notes
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: |
            dist/*
